_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
architecture:
    value: encoder_decoder_transformers
dataset:
    value: investment_dataset
epochs:
    value: 80
